version: 2
jobs:
  build:
    docker:
      - image: python:3-alpine
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date