version: 2
jobs:
  black:
    docker:
      - image: python:3-alpine
    steps:
      - checkout
      - run:
          name: Install Black
          command: pip install black
      - run:
          name: Run Black
          command: black --check .
  unit_test:
    docker:
      - image: python:3-alpine
    steps:
      - checkout
      - run:
          name: Run Tests
          command: python3 test.py

workflows:
  version: 2
  tests:
    jobs:
      - black
      - unit_test